import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu, Cairo } from "next/font/google";
import "./globals.css";
import Head from "next/head";
const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"]
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <Head>
        <link rel="icon" type="image/png" href="/images/favicon.png" />
      </Head>
      <body
        className={`${cairo.variable} ${ubuntu.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
